version: "3.8"
services:

    # PHP service
    app:
        build: .
        container_name: usar-php-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - app-network

    #adm do banco
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080        
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network


#rede de conexão
networks:
    # app-network é o nome da aplicação orquestrada
    app-network:
        driver: bridge
